// <auto-generated />
using Microsoft.Playwright;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using DFP.Playwright.Pages.Web.BasePages;
using DFP.Playwright.Helpers;

namespace DFP.Playwright.Pages.Web
{
    public sealed class DashboardPage : BasePage
    {
        private readonly string _dashboardUrl;

        public DashboardPage(IPage page) : base(page)
        {
            var baseUrl = Environment.GetEnvironmentVariable("BASE_URL") ?? "";
            var explicitDashboardUrl = Environment.GetEnvironmentVariable("DASHBOARD_URL") ?? "";
            if (!string.IsNullOrWhiteSpace(explicitDashboardUrl))
            {
                _dashboardUrl = explicitDashboardUrl;
            }
            else
            {
                _dashboardUrl = baseUrl.TrimEnd('/') + "/my-portal/dashboard?view=ops";
            }
        }

        private static readonly string[] ShipmentsSelectors =
        {
            "#navSidebar >> internal:role=link[name=\"Shipments\"i]",
            "internal:role=link[name=\"Shipments\"i]",
            "a:has-text(\"Shipments\")"
        };

        // <a href="/my-portal/dashboard?view=ops">Dashboard</a>  (sidebar nav link)
        private static readonly string[] DashboardNavSelectors =
        {
            "a[href='/my-portal/dashboard?view=ops']",
            "a[href*='/my-portal/dashboard']",
            "//a[contains(@href,'/my-portal/dashboard')]",
            "a >> internal:has-text=/^Dashboard$/",
            "//span[contains(@class,'nav-link-text') and normalize-space()='Dashboard']/.."
        };

        // Visible when dashboard ops data is loaded: "Here is a snapshot..." heading or stat cards
        private static readonly string[] DashboardVisibleSelectors =
        {
            "internal:text=\"Here is a snapshot of what's\"i",
            "//h6[normalize-space()='Active shipments']",
            "//a[contains(@href,'/shipments/list/sent')]"
        };

        // <h1><fa-icon svg[data-icon="paper-plane"]> 357 </h1>  — Active shipments count card
        private static readonly string[] ActiveShipmentsCountSelectors =
        {
            "h1:has(svg[data-icon='paper-plane'])",
            "//h1[.//*[@data-icon='paper-plane']]"
        };

        // <a href="/my-portal/reports"><span class="nav-link-text">Reports</span></a>
        private static readonly string[] ReportsSelectors =
        {
            "a[href='/my-portal/reports']",
            "//a[@href='/my-portal/reports']",
            "#navSidebar >> internal:role=link[name=\"Reports\"i]",
            "//span[contains(@class,'nav-link-text') and normalize-space()='Reports']/..",
            "a:has-text(\"Reports\")"
        };

        // codegen:selectors-start
        // Selectors captured by codegen for 'dashboard'
        public static readonly string[] Selectors = new[]
        {
            "#navSidebar >> internal:role=link[name=\"Shipments\"i]",
            "a >> internal:has-text=/^Dashboard$/",
            "internal:role=button[name=\"A\"s]",
            "internal:role=button[name=\"Shipments\"i]",
            "internal:role=heading[name=\"Shipments with upcoming events\"i]",
            "internal:role=link[name=\"Create shipment\"i]",
            "internal:text=\"Aylin Annia\"s",
            "internal:text=\"Here is a snapshot of what's\"i",
            "internal:text=\"Loading ops data...\"i",
        };
        // codegen:selectors-end

        public async Task IAmOnTheDashboardPage()
        {
            if (string.IsNullOrWhiteSpace(_dashboardUrl))
                throw new InvalidOperationException("BASE_URL/DASHBOARD_URL is required for dashboard navigation.");

            await Page.GotoAsync(_dashboardUrl);
            await FindLocatorAsync(ShipmentsSelectors);
        }

        public async Task IClickOnTheShipmentsOption()
        {
            var locator = await FindLocatorAsync(ShipmentsSelectors);
            await locator.ClickAsync();
        }

        public async Task IShouldSeeTheCreateShipmentsOption()
        {
            await FindLocatorAsync(ShipmentsSelectors);
        }

        public async Task IClickOnTheReportsOption()
        {
            var locator = await FindLocatorAsync(ReportsSelectors);
            await ClickAndWaitForNetworkAsync(locator);
        }

        public async Task IShouldSeeText(string expectedText)
        {
            var textEl = await TryFindLocatorAsync(new[]
            {
                $"//*[normalize-space()='{expectedText}']",
                $"internal:text=\"{expectedText}\"i",
                $"//*[contains(normalize-space(),'{expectedText}')]"
            }, timeoutMs: 15000);
            Assert.IsNotNull(textEl,
                $"Expected to see text '{expectedText}' on the page but it was not found. URL: {Page.Url}");
        }

        public async Task IClickOnDashboardIcon()
        {
            var dashboardLink = await FindLocatorAsync(DashboardNavSelectors);
            await ClickAndWaitForNavigationAsync(dashboardLink);
        }

        public async Task TheDashboardShouldBeVisible()
        {
            var dashboardEl = await TryFindLocatorAsync(DashboardVisibleSelectors, timeoutMs: 15000);
            Assert.IsNotNull(dashboardEl,
                $"Dashboard content was not visible after navigating. URL: {Page.Url}");
        }

        /// <summary>
        /// Finds the Active Shipments count card (paper-plane icon + number),
        /// extracts the numeric value and returns it.
        /// </summary>
        public async Task<int> GetTotalShipmentsCountAsync()
        {
            var h1 = await FindLocatorAsync(ActiveShipmentsCountSelectors);
            var rawText = await h1.InnerTextAsync();
            var match = Regex.Match(rawText, @"\d+");
            Assert.IsTrue(match.Success,
                $"Could not parse a number from the Active Shipments card. Raw text: '{rawText}'");
            return int.Parse(match.Value);
        }
    }
}







