// <auto-generated />
using Microsoft.Playwright;
using System;
using System.Threading.Tasks;
using DFP.Playwright.Pages.Web.BasePages;
using DFP.Playwright.Helpers;

namespace DFP.Playwright.Pages.Web
{
    public sealed class DashboardPage : BasePage
    {
        private readonly string _dashboardUrl;

        public DashboardPage(IPage page) : base(page)
        {
            var baseUrl = Environment.GetEnvironmentVariable("BASE_URL") ?? "";
            var explicitDashboardUrl = Environment.GetEnvironmentVariable("DASHBOARD_URL") ?? "";
            if (!string.IsNullOrWhiteSpace(explicitDashboardUrl))
            {
                _dashboardUrl = explicitDashboardUrl;
            }
            else
            {
                _dashboardUrl = baseUrl.TrimEnd('/') + "/my-portal/dashboard?view=ops";
            }
        }

        private static readonly string[] ShipmentsSelectors =
        {
            "#navSidebar >> internal:role=link[name=\"Shipments\"i]",
            "internal:role=link[name=\"Shipments\"i]",
            "a:has-text(\"Shipments\")"
        };

        // codegen:selectors-start
        // Selectors captured by codegen for 'dashboard'
        public static readonly string[] Selectors = new[]
        {
            "#navSidebar >> internal:role=link[name=\"Shipments\"i]",
            "a >> internal:has-text=/^Dashboard$/",
            "internal:role=button[name=\"A\"s]",
            "internal:role=button[name=\"Shipments\"i]",
            "internal:role=heading[name=\"Shipments with upcoming events\"i]",
            "internal:role=link[name=\"Create shipment\"i]",
            "internal:text=\"Aylin Annia\"s",
            "internal:text=\"Here is a snapshot of what's\"i",
            "internal:text=\"Loading ops data...\"i",
        };
        // codegen:selectors-end

        public async Task IAmOnTheDashboardPage()
        {
            if (string.IsNullOrWhiteSpace(_dashboardUrl))
                throw new InvalidOperationException("BASE_URL/DASHBOARD_URL is required for dashboard navigation.");

            await Page.GotoAsync(_dashboardUrl);
            await FindLocatorAsync(ShipmentsSelectors);
        }

        public async Task IClickOnTheShipmentsOption()
        {
            var locator = await FindLocatorAsync(ShipmentsSelectors);
            await locator.ClickAsync();
        }

        public async Task IShouldSeeTheCreateShipmentsOption()
        {
            await FindLocatorAsync(ShipmentsSelectors);
        }
    }
}







