// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace DFP.Playwright.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class HomeHubFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = new string[] {
                "HomeHub"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "HomeHub", "  As a user\n  I want to access to Home in the DFP Hub", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "HomeHub.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/HomeHub.feature.ndjson", 4);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Hub-Home_280")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Hub-Home_280")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "HomeHub")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("HomeHub")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("280")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("login")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NOINT")]
        public async global::System.Threading.Tasks.Task Hub_Home_280()
        {
            string[] tagsOfScenario = new string[] {
                    "280",
                    "login",
                    "NOINT"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Hub-Home_280", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await testRunner.GivenAsync("I login to Hub as user \"aylin.rodriguez@magaya.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
await testRunner.ThenAsync("the login dashboard should be visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 10
await testRunner.AndAsync("I should see the section header \"User Approvals\" in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
await testRunner.AndAsync("I should see the section header \"Quotation Requests\" in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
await testRunner.AndAsync("the \"Quotation Requests\" list should not be empty in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
await testRunner.AndAsync("I should see the section header \"Recent Notifications\" in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
await testRunner.AndAsync("the \"Recent Notifications\" list should not be empty in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
await testRunner.AndAsync("I should see the section header \"Your Sites\" in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
await testRunner.AndAsync("the \"Your Sites\" list should not be empty in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
await testRunner.WhenAsync("I click on \"View Quotations\" button in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
await testRunner.ThenAsync("I should see the \"quotations\" page in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 21
await testRunner.WhenAsync("I navigate to home in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
await testRunner.AndAsync("I click on \"View Shipments\" button in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
await testRunner.ThenAsync("I should see the \"shipments\" page in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 25
await testRunner.WhenAsync("I navigate to home in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 26
await testRunner.AndAsync("I click on \"portal users\" button in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
await testRunner.ThenAsync("I should see the \"Portal Users\" page in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 29
await testRunner.WhenAsync("I navigate to home in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 30
await testRunner.AndAsync("I click on \"profile\" button in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
await testRunner.ThenAsync("I should see the \"About\" page in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 33
await testRunner.WhenAsync("I navigate to home in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 34
await testRunner.AndAsync("I click on the first View button in Recent Notifications in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
await testRunner.ThenAsync("I should be redirected to a page with the Qwyk breadcrumb in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Hub - Hub - Recent Notifications_811")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Hub - Hub - Recent Notifications_811")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "HomeHub")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("HomeHub")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("811")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("login")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NOINT")]
        public async global::System.Threading.Tasks.Task Hub_Hub_RecentNotifications_811()
        {
            string[] tagsOfScenario = new string[] {
                    "811",
                    "login",
                    "NOINT"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Hub - Hub - Recent Notifications_811", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 38
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 39
await testRunner.GivenAsync("I login to Hub as user \"aylin.rodriguez@magaya.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 40
await testRunner.ThenAsync("the login dashboard should be visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 41
await testRunner.AndAsync("I should see the section header \"Recent Notifications\" in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
await testRunner.AndAsync("the \"Recent Notifications\" list should not be empty in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
await testRunner.AndAsync("I click on the first View button in Recent Notifications in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
await testRunner.ThenAsync("I should be redirected to a page with the Qwyk breadcrumb in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
