// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace DFP.Playwright.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class HubRadarFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = new string[] {
                "HubRadar"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "HubRadar", "  As a user\n  I want to access to Radar in the DFP Hub", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "HubRadar.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/HubRadar.feature.ndjson", 3);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Hub-Radar_281")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Hub-Radar_281")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "HubRadar")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("HubRadar")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("281")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NOINT")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("login")]
        public async global::System.Threading.Tasks.Task Hub_Radar_281()
        {
            string[] tagsOfScenario = new string[] {
                    "281",
                    "NOINT",
                    "login"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Hub-Radar_281", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await testRunner.GivenAsync("I login to Hub as user \"aylin.rodriguez@magaya.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
await testRunner.ThenAsync("the login dashboard should be visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 10
await testRunner.WhenAsync("I navigate to radar page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 11
await testRunner.ThenAsync("I should see the section header \"Sales\" in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 12
await testRunner.WhenAsync("I click on view sales radar", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
await testRunner.ThenAsync("I should see the section header \"Sales Radar\" in the Hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 15
await testRunner.ThenAsync("I verify Performance over Time section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 17
await testRunner.AndAsync("I verify Rankings section", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
await testRunner.AndAsync("I verify Data Table section", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
await testRunner.WhenAsync("I filter radar by period \"1w\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
await testRunner.ThenAsync("the radar charts are visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 24
await testRunner.WhenAsync("I open radar filters", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
await testRunner.AndAsync("I filter radar by transport mode \"AIR\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
await testRunner.AndAsync("I apply radar filters", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
await testRunner.WhenAsync("I click the radar refresh button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
await testRunner.ThenAsync("the radar charts are visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 29
await testRunner.AndAsync("the data table column \"Transport Mode\" should have value \"AIR\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
await testRunner.WhenAsync("I reset radar filters", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
await testRunner.WhenAsync("I open radar filters", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
await testRunner.AndAsync("I filter radar by load type \"LCL/LTL\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
await testRunner.AndAsync("I apply radar filters", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
await testRunner.WhenAsync("I click the radar refresh button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 36
await testRunner.ThenAsync("the radar charts are visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 37
await testRunner.AndAsync("the data table column \"Load type\" should have value \"lcl\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
await testRunner.WhenAsync("I reset radar filters", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 40
await testRunner.WhenAsync("I open radar filters", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
await testRunner.AndAsync("I filter radar by account manager \"Aylin Rodriguez\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
await testRunner.AndAsync("I apply radar filters", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
await testRunner.WhenAsync("I click the radar refresh button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 44
await testRunner.ThenAsync("the radar charts are visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 45
await testRunner.AndAsync("the data table column \"Account manager\" should have value \"Aylin Rodriguez,Automa" +
                        "tionHub,AutomationHub\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 47
await testRunner.WhenAsync("I reset radar filters", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 48
await testRunner.WhenAsync("I click the radar refresh button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
await testRunner.ThenAsync("the radar charts are visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 51
await testRunner.WhenAsync("I click the radar full screen button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 52
await testRunner.ThenAsync("the radar is displayed in full screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 53
await testRunner.AndAsync("I exit full screen mode", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
await testRunner.WhenAsync("I filter radar rankings by metric \"Quotation Value\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 56
await testRunner.AndAsync("I click the radar refresh button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
await testRunner.ThenAsync("the radar charts are visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 59
await testRunner.WhenAsync("I export radar data to CSV", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 60
await testRunner.ThenAsync("a radar file is downloaded", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 62
await testRunner.WhenAsync("I export radar data to Excel", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 63
await testRunner.ThenAsync("a radar file is downloaded", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
