// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace DFP.Playwright.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class InventoryFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = new string[] {
                "Inventory"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Inventory", "    As a user\n    I want to manage inventory in the DFP Portal", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Inventory.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Inventory.feature.ndjson", 4);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("1307_MagayaToQWYK_InventoryItem")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("1307_MagayaToQWYK_InventoryItem")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Inventory")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Inventory")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("1307")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("INT")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("login")]
        public async global::System.Threading.Tasks.Task _1307_MagayaToQWYK_InventoryItem()
        {
            string[] tagsOfScenario = new string[] {
                    "1307",
                    "INT",
                    "login"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("1307_MagayaToQWYK_InventoryItem", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync("the transaction \"IV\" \"Mar31155414InvItem\" is imported via API", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
    await testRunner.GivenAsync("I login to Portal as user \"with Int\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 10
    await testRunner.ThenAsync("the login dashboard should be visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 11
    await testRunner.GivenAsync("I am on the Inventory page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 12
    await testRunner.ThenAsync("the inventory page should be visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 13
    await testRunner.GivenAsync("I search for the inventory item \"Part number\" with value \"Mar31155414InvItem\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 14
    await testRunner.ThenAsync("I click on \"Search\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 15
    await testRunner.ThenAsync("the inventory item should be visible in the List", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 16
    await testRunner.ThenAsync("I select the inventory item from the list with text \"Mar31155414InvItem\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 17
    await testRunner.ThenAsync("I should see the inventory item details page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "Part number",
                            "Mar31155414InvItem"});
                table13.AddRow(new string[] {
                            "Model",
                            "Mar31155415InvModel"});
                table13.AddRow(new string[] {
                            "Description",
                            "Mar31155415InvDescription"});
                table13.AddRow(new string[] {
                            "Manufacturer",
                            "automation"});
                table13.AddRow(new string[] {
                            "Customer",
                            "automation"});
                table13.AddRow(new string[] {
                            "Amount per pallet",
                            "10"});
                table13.AddRow(new string[] {
                            "Packaging",
                            "Pallet"});
                table13.AddRow(new string[] {
                            "Commodity type",
                            "Freight All Kinds"});
#line 18
    await testRunner.ThenAsync("I should verify the following inventory item details:", ((string)(null)), table13, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("1308_MagayaToQWYK_UpdateInvItem")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("1308_MagayaToQWYK_UpdateInvItem")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Inventory")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Inventory")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("1308")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("INT")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("login")]
        public async global::System.Threading.Tasks.Task _1308_MagayaToQWYK_UpdateInvItem()
        {
            string[] tagsOfScenario = new string[] {
                    "1308",
                    "INT",
                    "login"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("1308_MagayaToQWYK_UpdateInvItem", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 29
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 30
    await testRunner.GivenAsync("the transaction \"IV\" \"TC1308\" is imported via API", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 31
    await testRunner.GivenAsync("I login to Portal as user \"with Int\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 32
    await testRunner.ThenAsync("the login dashboard should be visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 33
    await testRunner.GivenAsync("I am on the Inventory page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 34
    await testRunner.ThenAsync("the inventory page should be visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 35
    await testRunner.GivenAsync("I search for the inventory item \"Part number\" with value \"TC1308\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 36
    await testRunner.ThenAsync("I click on \"Search\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 37
    await testRunner.ThenAsync("the inventory item should be visible in the List", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 38
    await testRunner.ThenAsync("I select the inventory item from the list with text \"TC1308\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 39
    await testRunner.ThenAsync("I should see the inventory item details page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "Part number",
                            "TC1308"});
                table14.AddRow(new string[] {
                            "Model",
                            "Apr01111816InvModel"});
                table14.AddRow(new string[] {
                            "Description",
                            "Apr01111816InvDescription"});
                table14.AddRow(new string[] {
                            "Manufacturer",
                            "automation"});
                table14.AddRow(new string[] {
                            "Customer",
                            "automation"});
                table14.AddRow(new string[] {
                            "Amount per pallet",
                            "10"});
                table14.AddRow(new string[] {
                            "Packaging",
                            "Pallet"});
                table14.AddRow(new string[] {
                            "Commodity type",
                            "Freight All Kinds"});
#line 40
    await testRunner.ThenAsync("I should verify the following inventory item details:", ((string)(null)), table14, "Then ");
#line hidden
#line 52
    await testRunner.GivenAsync("I am on the Inventory page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 53
    await testRunner.ThenAsync("the inventory page should be visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 54
    await testRunner.GivenAsync("I search for the inventory item \"Part number\" with value \"TC1308\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 55
    await testRunner.ThenAsync("I click on \"Search\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 56
    await testRunner.ThenAsync("the inventory item should be visible in the List", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 57
    await testRunner.ThenAsync("I select the inventory item from the list with text \"Updated\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 58
    await testRunner.ThenAsync("I should see the inventory item details page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "Part number",
                            "TC1308"});
                table15.AddRow(new string[] {
                            "Model",
                            "Updated"});
                table15.AddRow(new string[] {
                            "Description",
                            "Updated"});
                table15.AddRow(new string[] {
                            "Notes",
                            "InventoryItemUpdated"});
                table15.AddRow(new string[] {
                            "Manufacturer",
                            "automation"});
                table15.AddRow(new string[] {
                            "Customer",
                            "automation"});
                table15.AddRow(new string[] {
                            "Amount per pallet",
                            "500"});
                table15.AddRow(new string[] {
                            "Packaging",
                            "Package"});
                table15.AddRow(new string[] {
                            "Commodity type",
                            "Freight All Kinds"});
#line 59
    await testRunner.ThenAsync("I should verify the following inventory item details:", ((string)(null)), table15, "Then ");
#line hidden
#line 69
    await testRunner.ThenAsync("I should verify the total pieces in the inventory item details page is \"100\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 70
    await testRunner.ThenAsync("I click on On Hand icon", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 71
    await testRunner.GivenAsync("I set the warehouse receipt name to \"TC1308\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 72
    await testRunner.AndAsync("I enter the warehouse receipt name in search field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 73
    await testRunner.AndAsync("I click on Search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 74
    await testRunner.ThenAsync("the warehouse receipt should appear in the search results in the List with text \"" +
                        "automation\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 75
    await testRunner.AndAsync("I select the warehouse receipt in the search results with text \"automation\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 76
    await testRunner.AndAsync("the warehouse receipt details should be displayed with the name \"TC1308\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
    await testRunner.AndAsync("I should verify label header \"Number\" contains \"TC1308\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "Number",
                            "TC1308"});
                table16.AddRow(new string[] {
                            "Supplier",
                            "automation"});
                table16.AddRow(new string[] {
                            "Billing Client",
                            "automation"});
#line 78
    await testRunner.AndAsync("I should verify the following label headers in warehouse receipt details:", ((string)(null)), table16, "And ");
#line hidden
#line 83
    await testRunner.WhenAsync("I go to cargo tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 84
    await testRunner.ThenAsync("I should see the cargo items page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 85
    await testRunner.ThenAsync("I should see the commodity \"Updated\" in cargo details warehouse", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 86
    await testRunner.ThenAsync("I should see the text \"TC1308\" in the cargo items column", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 87
    await testRunner.ThenAsync("I should see the text \"100x Package\" in the cargo items column", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
