// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace DFP.Playwright.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class MailingRulesHubFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Mailing Rules Hub", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "MailingRulesHub.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/MailingRulesHub.feature.ndjson", 3);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Mailing Rules - New Shipment/All options - An email is sent to HUB Users, Mailing" +
            " List users and Customer Related users")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Mailing Rules - New Shipment/All options - An email is sent to HUB Users, Mailing" +
            " List users and Customer Related users")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Mailing Rules Hub")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("7831")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NOINT")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("login")]
        public async global::System.Threading.Tasks.Task MailingRules_NewShipmentAllOptions_AnEmailIsSentToHUBUsersMailingListUsersAndCustomerRelatedUsers()
        {
            string[] tagsOfScenario = new string[] {
                    "7831",
                    "NOINT",
                    "login"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Mailing Rules - New Shipment/All options - An email is sent to HUB Users, Mailing" +
                    " List users and Customer Related users", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await testRunner.GivenAsync("I login to Hub as user \"aylin.rodriguez@magaya.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 6
await testRunner.ThenAsync("the login dashboard should be visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 7
await testRunner.WhenAsync("I go to Admin Portal Notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 8
await testRunner.ThenAsync("I should see the Create Mailing List button", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 9
await testRunner.WhenAsync("I search the mailing list by Name \"AutomationMailingList\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
await testRunner.ThenAsync("I click on search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 11
await testRunner.AndAsync("I check if the list exists to delete it", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
await testRunner.WhenAsync("I click on Create Mailing List button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
await testRunner.ThenAsync("I enter the name of the mailing \"AutomationMailingList\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 14
await testRunner.AndAsync("I click on Create mailing List", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
await testRunner.AndAsync("I should see the Create Mailing List button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
await testRunner.WhenAsync("I select the created mailing list \"AutomationMailingList\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 17
await testRunner.ThenAsync("I should see the available members list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 19
await testRunner.AndAsync("I enter the email \"automationhub@yopmail.com\" to add the member", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
await testRunner.AndAsync("I add the member", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
await testRunner.WhenAsync("I save the list", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
await testRunner.ThenAsync("I should see the Create Mailing List button", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 23
await testRunner.WhenAsync("I go to Mailing Rules", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 24
await testRunner.ThenAsync("I should see the Mailing Rules", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 25
await testRunner.WhenAsync("I search the mailing rule by Name \"AutomationMailingRule\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 26
await testRunner.ThenAsync("I click on search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 27
await testRunner.AndAsync("I check if the Rule exists to delete it", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
await testRunner.WhenAsync("I click on Create Rule button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 29
await testRunner.ThenAsync("I should see the view to create the Rule", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 30
await testRunner.AndAsync("I enter the Mailing Rule Name \"AutomationMailingRule\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
await testRunner.AndAsync("I select the Notification Type \"New Booking Created\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
await testRunner.WhenAsync("I click on Create Mailing Rule", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 35
await testRunner.ThenAsync("I should select the Mailing List \"AutomationMailingList\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 36
await testRunner.AndAsync("I should see the Mailing List \"AutomationMailingList\" in the Recipients tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
await testRunner.WhenAsync("I select the Hub User \"Aylin QuotationOP\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
await testRunner.ThenAsync("I should see the Name \"Aylin QuotationOP\" in the Hub Users Recipients", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 40
await testRunner.WhenAsync("I go to Customers tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
await testRunner.ThenAsync("I select the Customer \"Customer 1\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 43
await testRunner.WhenAsync("I click on save Mailing Rule button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 44
await testRunner.ThenAsync("I should see the Mailing Rules", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 46
await testRunner.GivenAsync("I login to Portal as user \"aylinportalinfra@yopmail.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 47
await testRunner.GivenAsync("I am on the Quotations List page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 48
    await testRunner.WhenAsync("I open the first quotation in Status Booked", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
    await testRunner.ThenAsync("I should be on the Quotation Details page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 50
    await testRunner.WhenAsync("I click the \"Offers\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 51
    await testRunner.ThenAsync("the list of the offers should appear", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 52
    await testRunner.WhenAsync("I click on Book Now button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 53
    await testRunner.ThenAsync("a confirmation dialog should appear", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 54
    await testRunner.WhenAsync("I confirm the shipment creation", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
    await testRunner.ThenAsync("I should be on the Shipment Details page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 56
    await testRunner.ThenAsync("I store the shipment id from the URL", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 57
    await testRunner.WhenAsync("I click on Edit button to Edit the Shipment Name", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 58
    await testRunner.ThenAsync("I should edit the Shipment Name", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 59
    await testRunner.AndAsync("I store shipment Name", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
    await testRunner.WhenAsync("I click on save button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 61
    await testRunner.ThenAsync("I should see the new Shipment Name", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 62
    await testRunner.WhenAsync("I click on Send Booking button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 63
    await testRunner.ThenAsync("I should click on Go To Shipment button to see the shipment", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 64
    await testRunner.AndAsync("the shipment should display the shipment name", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
await testRunner.WhenAsync("I Check the email for \"automationhub@yopmail.com\" with username \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 67
await testRunner.ThenAsync("I should receive an email with text \"A new shipment was booked.|Shipment:\" in the" +
                        " body for shipment \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 69
await testRunner.WhenAsync("I Check the email for \"aylinquotationop@yopmail.com\" with username \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 70
await testRunner.ThenAsync("I should receive an email with text \"A new shipment was booked.|Shipment:\" in the" +
                        " body for shipment \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 72
await testRunner.WhenAsync("I Check the email for \"child_noint@yopmail.com\" with username \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
await testRunner.ThenAsync("I should receive an email with text \"A new shipment was booked.|Shipment:\" in the" +
                        " body for shipment \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 75
await testRunner.GivenAsync("I login to Hub as user \"aylinquotationop@yopmail.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 76
    await testRunner.ThenAsync("the login dashboard should be visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 77
    await testRunner.AndAsync("I should see the last notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
    await testRunner.AndAsync("I should see the notification related to the created Shipment \"booked a new shipm" +
                        "ent\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 79
    await testRunner.WhenAsync("I click on View shipment button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 80
    await testRunner.ThenAsync("I should see the shipment details", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
