// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace DFP.Playwright.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class WarehouseReceiptsFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = new string[] {
                "WarehouseReceipts"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Warehouse Receipts", "    As a user\n    I want to verify that Warehouse Receipts with Exclude from Trac" +
                "king enabled in Magaya\n    are not visible in the DFP Portal", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Warehouse.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Warehouse.feature.ndjson", 7);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Magaya to DFP - Warehouse Receipt - Exclude from Tracking = True")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Magaya to DFP - Warehouse Receipt - Exclude from Tracking = True")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Warehouse Receipts")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WarehouseReceipts")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("3907")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("INT")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("login")]
        public async global::System.Threading.Tasks.Task MagayaToDFP_WarehouseReceipt_ExcludeFromTrackingTrue()
        {
            string[] tagsOfScenario = new string[] {
                    "3907",
                    "INT",
                    "login"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Magaya to DFP - Warehouse Receipt - Exclude from Tracking = True", "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 9
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
    await testRunner.GivenAsync("I login to Portal as user \"with Int\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 13
    await testRunner.GivenAsync("I navigated to Warehouse Receipts List", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 14
    await testRunner.GivenAsync("I set the warehouse receipt name to \"TC3907\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 15
    await testRunner.AndAsync("I enter the warehouse receipt name in search field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
    await testRunner.AndAsync("I click on Search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
    await testRunner.ThenAsync("the warehouse receipt should not appear in the search results", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 19
    await testRunner.GivenAsync("I navigated to Cargo Detail Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 20
    await testRunner.ThenAsync("I enter the warehouse receipt name in search field in Cargo Detail", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 21
    await testRunner.AndAsync("I click on Search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
    await testRunner.ThenAsync("the warehouse receipt should not be displayed in Cargo Detail", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 24
    await testRunner.WhenAsync("I go to Reports Warehouse", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
    await testRunner.ThenAsync("I should see \"Generate Warehouse Receipts\" Report text", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 26
    await testRunner.AndAsync("I click on Search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
    await testRunner.WhenAsync("I see the Save report button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
    await testRunner.ThenAsync("the warehouse receipt name should not appear in the report results", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("User edits a Table View and verifies selected columns")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("User edits a Table View and verifies selected columns")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Warehouse Receipts")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WarehouseReceipts")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("5439")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("login")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("INT")]
        public async global::System.Threading.Tasks.Task UserEditsATableViewAndVerifiesSelectedColumns()
        {
            string[] tagsOfScenario = new string[] {
                    "5439",
                    "login",
                    "INT"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("User edits a Table View and verifies selected columns", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 31
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 32
    await testRunner.GivenAsync("I login to Portal as user \"with Int\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 33
    await testRunner.GivenAsync("I navigated to Warehouse Receipts List", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 34
    await testRunner.WhenAsync("I click on Table View in WH Receipt List", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 35
    await testRunner.AndAsync("I select a view to edit", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
    await testRunner.AndAsync("I click on Configuration button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
    await testRunner.AndAsync("I click on Columns tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
    await testRunner.AndAsync("I enter the column Name in the field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
    await testRunner.AndAsync("I select the column Name", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
    await testRunner.AndAsync("I close the Customize View", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
    await testRunner.ThenAsync("I should see the selected columns in the Table View", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Verify Customs fields in Warehouse Receipt")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Verify Customs fields in Warehouse Receipt")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Warehouse Receipts")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WarehouseReceipts")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("3072")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("API")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("INT")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("login")]
        public async global::System.Threading.Tasks.Task VerifyCustomsFieldsInWarehouseReceipt()
        {
            string[] tagsOfScenario = new string[] {
                    "3072",
                    "API",
                    "INT",
                    "login"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify Customs fields in Warehouse Receipt", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 44
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 45
    await testRunner.GivenAsync("the transaction \"WH\" \"TC3072\" is imported via API", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 46
    await testRunner.GivenAsync("I login to Portal as user \"with Int\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 48
    await testRunner.GivenAsync("I navigated to Warehouse Receipts List", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 49
    await testRunner.GivenAsync("I set the warehouse receipt name to \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 50
    await testRunner.AndAsync("I enter the warehouse receipt name in search field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
    await testRunner.WhenAsync("I click on Table View in WH Receipt List", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 52
    await testRunner.AndAsync("I click on Search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 53
    await testRunner.ThenAsync("the warehouse receipt should appear in the search results", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 54
    await testRunner.AndAsync("I check the custom field \"StringCustomField\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "StringCustomField",
                            "STRINGCUSTOMFIELD3072"});
                table14.AddRow(new string[] {
                            "BooleanCustomField",
                            "No"});
                table14.AddRow(new string[] {
                            "IntegerCustomField",
                            "3072"});
                table14.AddRow(new string[] {
                            "DecimalCustomField",
                            "30.72"});
                table14.AddRow(new string[] {
                            "PickListCustomField",
                            "Option1"});
                table14.AddRow(new string[] {
                            "DateCustomField",
                            "02/24/2026"});
                table14.AddRow(new string[] {
                            "MoneyCustomField",
                            "USD 30.72"});
                table14.AddRow(new string[] {
                            "LookupCutomsField",
                            "automationUpdated"});
                table14.AddRow(new string[] {
                            "QATest",
                            "QATEST3072"});
                table14.AddRow(new string[] {
                            "GUIDWH",
                            "GUID"});
#line 55
    await testRunner.AndAsync("I check the following custom field values in the table view:", ((string)(null)), table14, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("923_3373MagayaToQWYK_WarehouseReceipt")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("923_3373MagayaToQWYK_WarehouseReceipt")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Warehouse Receipts")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WarehouseReceipts")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("923")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("3373")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("API")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("INT")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("login")]
        public async global::System.Threading.Tasks.Task _923_3373MagayaToQWYK_WarehouseReceipt()
        {
            string[] tagsOfScenario = new string[] {
                    "923",
                    "3373",
                    "API",
                    "INT",
                    "login"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("923_3373MagayaToQWYK_WarehouseReceipt", "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 70
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 72
    await testRunner.GivenAsync("the transaction \"WH\" \"TC923_3373\" is imported via API", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 73
    await testRunner.GivenAsync("I login to Portal as user \"with Int\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 75
    await testRunner.GivenAsync("I navigated to Warehouse Receipts List", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 76
    await testRunner.GivenAsync("I set the warehouse receipt name to \"TC923_3373\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 77
    await testRunner.AndAsync("I enter the warehouse receipt name in search field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
    await testRunner.AndAsync("I click on Search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 79
    await testRunner.ThenAsync("the warehouse receipt should appear in the search results in the List with text \"" +
                        "automation\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 80
    await testRunner.AndAsync("I select the warehouse receipt in the search results with text \"automation\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 81
    await testRunner.AndAsync("the warehouse receipt details should be displayed with the name \"TC923_3373\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 82
    await testRunner.AndAsync("I should verify label header \"Number\" contains \"TC923_3373\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "Number",
                            "TC923_3373"});
                table15.AddRow(new string[] {
                            "Carrier PRO Number",
                            "1485PONumber"});
                table15.AddRow(new string[] {
                            "Carrier Tracking Number",
                            "1485TrackingNumber"});
                table15.AddRow(new string[] {
                            "Driver",
                            "1485DriverName"});
                table15.AddRow(new string[] {
                            "License",
                            "1485LicenseNumber"});
                table15.AddRow(new string[] {
                            "Supplier",
                            "automation"});
                table15.AddRow(new string[] {
                            "PO Number",
                            "1485PONumber"});
                table15.AddRow(new string[] {
                            "PO Invoice Number",
                            "1485INVNumber"});
                table15.AddRow(new string[] {
                            "Billing Client",
                            "automation"});
                table15.AddRow(new string[] {
                            "Note",
                            "1485WR created in Magaya"});
#line 83
    await testRunner.AndAsync("I should verify the following label headers in warehouse receipt details:", ((string)(null)), table15, "And ");
#line hidden
#line 96
    await testRunner.AndAsync("I should verify custom fields label header \"BooleanCustomField\" contains \"Yes\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "BooleanCustomField",
                            "Yes"});
                table16.AddRow(new string[] {
                            "DateCustomField",
                            "01/25/2025"});
                table16.AddRow(new string[] {
                            "DecimalCustomField",
                            "0.5"});
                table16.AddRow(new string[] {
                            "IntegerCustomField",
                            "10"});
                table16.AddRow(new string[] {
                            "MoneyCustomField",
                            "USD 50"});
                table16.AddRow(new string[] {
                            "PickListCustomField",
                            "Option1"});
                table16.AddRow(new string[] {
                            "StringCustomField",
                            "StringCustom"});
                table16.AddRow(new string[] {
                            "GUIDWH",
                            "GUID"});
                table16.AddRow(new string[] {
                            "LookupCutomsField",
                            "automation"});
                table16.AddRow(new string[] {
                            "QATest",
                            "QAAutomationTests"});
#line 97
    await testRunner.AndAsync("I should verify the following custom field values in warehouse receipt details in" +
                        " DFP:", ((string)(null)), table16, "And ");
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "Billing Client",
                            "automation"});
                table17.AddRow(new string[] {
                            "Carrier",
                            "MSC"});
                table17.AddRow(new string[] {
                            "Consignee",
                            "automation"});
                table17.AddRow(new string[] {
                            "Destination Agent",
                            "AgentDestination"});
                table17.AddRow(new string[] {
                            "Issued By",
                            "Postgress SQL II"});
                table17.AddRow(new string[] {
                            "Shipper",
                            "automation"});
                table17.AddRow(new string[] {
                            "Supplier",
                            "automation"});
#line 110
    await testRunner.AndAsync("I should verify the following parties in warehouse receipt details:", ((string)(null)), table17, "And ");
#line hidden
#line 120
    await testRunner.WhenAsync("I go to tracking tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 121
    await testRunner.ThenAsync("I should see the event \"Arrived at warehouse\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 123
    await testRunner.WhenAsync("I go to cargo tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 124
    await testRunner.ThenAsync("I should see the cargo items page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 125
    await testRunner.AndAsync("I should see the commodity \"UpdateCommodity\" in cargo details warehouse", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 127
    await testRunner.WhenAsync("I go to charge and invoice tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 128
    await testRunner.AndAsync("I should see the amount \"$150.00\" for the charge \"Cartage Fee\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 130
    await testRunner.WhenAsync("I go to attachments tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 131
    await testRunner.AndAsync("I select the pagination number \"50\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 132
    await testRunner.AndAsync("I should see the uploaded file \"test.jpg\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 133
    await testRunner.AndAsync("I should see the uploaded file \"test2.pdf\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 135
    await testRunner.AndAsync("I should see the uploaded file \"DOCDFP.docx\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 136
    await testRunner.AndAsync("I should see the uploaded file \"MSGDFP.msg\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 137
    await testRunner.AndAsync("I should see the uploaded file \"test1.png\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 138
    await testRunner.AndAsync("I should see the uploaded file \"CSVDFP.csv\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 139
    await testRunner.AndAsync("I should see the uploaded file \"test.jpg\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 140
    await testRunner.AndAsync("I should see the uploaded file \"TXT_MAGAYA.txt\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 141
    await testRunner.AndAsync("I should see the uploaded file \"XML_MAGAYA.xml\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 142
    await testRunner.AndAsync("I should see the uploaded file \"JSON_MAGAYA.json\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 143
    await testRunner.AndAsync("I should see the uploaded file \"XLSDFP.xlsx\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 144
    await testRunner.AndAsync("I should see the uploaded file \"PDFDFP.pdf\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("924_MagayaToQWYK_UpdateWR")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("924_MagayaToQWYK_UpdateWR")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Warehouse Receipts")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WarehouseReceipts")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("924")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("API")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("INT")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("login")]
        public async global::System.Threading.Tasks.Task _924_MagayaToQWYK_UpdateWR()
        {
            string[] tagsOfScenario = new string[] {
                    "924",
                    "API",
                    "INT",
                    "login"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("924_MagayaToQWYK_UpdateWR", "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 147
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 149
    await testRunner.GivenAsync("the transaction \"WH\" \"TC924\" is imported via API", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 150
    await testRunner.GivenAsync("I login to Portal as user \"with Int\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 152
    await testRunner.GivenAsync("I navigated to Warehouse Receipts List", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 153
    await testRunner.GivenAsync("I set the warehouse receipt name to \"TC924\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 154
    await testRunner.AndAsync("I enter the warehouse receipt name in search field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 155
    await testRunner.AndAsync("I click on Search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 156
    await testRunner.ThenAsync("the warehouse receipt should appear in the search results in the List with text \"" +
                        "automation\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 157
    await testRunner.AndAsync("I select the warehouse receipt in the search results with text \"automation\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 158
    await testRunner.AndAsync("the warehouse receipt details should be displayed with the name \"TC924\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 159
    await testRunner.AndAsync("I should verify label header \"Number\" contains \"TC924\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "Number",
                            "TC924"});
                table18.AddRow(new string[] {
                            "Carrier PRO Number",
                            "1487PONumber"});
                table18.AddRow(new string[] {
                            "Carrier Tracking Number",
                            "1487TrackingNumber"});
                table18.AddRow(new string[] {
                            "Driver",
                            "1487DriverName"});
                table18.AddRow(new string[] {
                            "License",
                            "1487LicenseNumber"});
                table18.AddRow(new string[] {
                            "Supplier",
                            "automation"});
                table18.AddRow(new string[] {
                            "PO Number",
                            "1487PONumber"});
                table18.AddRow(new string[] {
                            "PO Invoice Number",
                            "1487INVNumber"});
                table18.AddRow(new string[] {
                            "Billing Client",
                            "automation"});
                table18.AddRow(new string[] {
                            "Note",
                            "1487WR created in Magaya"});
#line 160
    await testRunner.AndAsync("I should verify the following label headers in warehouse receipt details:", ((string)(null)), table18, "And ");
#line hidden
#line 173
    await testRunner.AndAsync("I should verify custom fields label header \"BooleanCustomField\" contains \"Yes\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                            "BooleanCustomField",
                            "Yes"});
                table19.AddRow(new string[] {
                            "DateCustomField",
                            "01/25/2025"});
                table19.AddRow(new string[] {
                            "DecimalCustomField",
                            "0.5"});
                table19.AddRow(new string[] {
                            "IntegerCustomField",
                            "10"});
                table19.AddRow(new string[] {
                            "MoneyCustomField",
                            "USD 50"});
                table19.AddRow(new string[] {
                            "PickListCustomField",
                            "Option1"});
                table19.AddRow(new string[] {
                            "StringCustomField",
                            "StringCustom"});
                table19.AddRow(new string[] {
                            "GUIDWH",
                            "GUID"});
                table19.AddRow(new string[] {
                            "LookupCutomsField",
                            "automation"});
                table19.AddRow(new string[] {
                            "QATest",
                            "QAAutomationTests"});
#line 174
    await testRunner.AndAsync("I should verify the following custom field values in warehouse receipt details in" +
                        " DFP:", ((string)(null)), table19, "And ");
#line hidden
                global::Reqnroll.Table table20 = new global::Reqnroll.Table(new string[] {
                            "Billing Client",
                            "automation"});
                table20.AddRow(new string[] {
                            "Carrier",
                            "MSC"});
                table20.AddRow(new string[] {
                            "Consignee",
                            "automation"});
                table20.AddRow(new string[] {
                            "Destination Agent",
                            "AgentDestination"});
                table20.AddRow(new string[] {
                            "Issued By",
                            "Postgress SQL II"});
                table20.AddRow(new string[] {
                            "Shipper",
                            "automation"});
                table20.AddRow(new string[] {
                            "Supplier",
                            "automation"});
#line 187
    await testRunner.AndAsync("I should verify the following parties in warehouse receipt details:", ((string)(null)), table20, "And ");
#line hidden
#line 197
    await testRunner.WhenAsync("I go to tracking tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 198
    await testRunner.ThenAsync("I should see the event \"Arrived at warehouse\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 200
    await testRunner.WhenAsync("I go to cargo tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 201
    await testRunner.ThenAsync("I should see the cargo items page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 202
    await testRunner.AndAsync("I should see the commodity \"UpdateCommodity\" in cargo details warehouse", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 204
    await testRunner.WhenAsync("I go to charge and invoice tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 205
    await testRunner.AndAsync("I should see the amount \"$150.00\" for the charge \"Cartage Fee\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 207
    await testRunner.WhenAsync("I go to attachments tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 208
    await testRunner.AndAsync("I select the pagination number \"50\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 209
    await testRunner.AndAsync("I should see the uploaded file \"test.jpg\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 211
    await testRunner.AndAsync("I should see the uploaded file \"test2.pdf\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 218
    await testRunner.GivenAsync("I navigated to Warehouse Receipts List", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 219
    await testRunner.GivenAsync("I set the warehouse receipt name to \"TC924UPDATED\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 220
    await testRunner.AndAsync("I enter the warehouse receipt name in search field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 221
    await testRunner.AndAsync("I click on Search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 222
    await testRunner.ThenAsync("the warehouse receipt should appear in the search results in the List with text \"" +
                        "automation\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 223
    await testRunner.AndAsync("I select the warehouse receipt in the search results with text \"automation\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 224
    await testRunner.AndAsync("the warehouse receipt details should be displayed with the name \"TC924UPDATED\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 225
    await testRunner.AndAsync("I should verify label header \"Number\" contains \"TC924UPDATED\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table21 = new global::Reqnroll.Table(new string[] {
                            "Number",
                            "TC924UPDATED"});
                table21.AddRow(new string[] {
                            "Carrier PRO Number",
                            "1487PONumberUpdated"});
                table21.AddRow(new string[] {
                            "Carrier Tracking Number",
                            "1487TrackingNumberUpdated"});
                table21.AddRow(new string[] {
                            "Driver",
                            "1487DriverNameUpdated"});
                table21.AddRow(new string[] {
                            "License",
                            "1487LicenseNumberUpdated"});
                table21.AddRow(new string[] {
                            "Supplier",
                            "automation"});
                table21.AddRow(new string[] {
                            "PO Number",
                            "1487PONumberUpdated"});
                table21.AddRow(new string[] {
                            "PO Invoice Number",
                            "1487INVNumber"});
                table21.AddRow(new string[] {
                            "Billing Client",
                            "automation"});
                table21.AddRow(new string[] {
                            "Note",
                            "NOTE UPDATED"});
#line 226
    await testRunner.AndAsync("I should verify the following label headers in warehouse receipt details:", ((string)(null)), table21, "And ");
#line hidden
#line 239
    await testRunner.AndAsync("I should verify custom fields label header \"BooleanCustomField\" contains \"Yes\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                            "BooleanCustomField",
                            "Yes"});
                table22.AddRow(new string[] {
                            "DateCustomField",
                            "01/25/2025"});
                table22.AddRow(new string[] {
                            "DecimalCustomField",
                            "600"});
                table22.AddRow(new string[] {
                            "IntegerCustomField",
                            "400"});
                table22.AddRow(new string[] {
                            "MoneyCustomField",
                            "USD 700"});
                table22.AddRow(new string[] {
                            "PickListCustomField",
                            "Option2"});
                table22.AddRow(new string[] {
                            "StringCustomField",
                            "ShipperRefUpdated"});
                table22.AddRow(new string[] {
                            "GUIDWH",
                            "GUIDUpdated"});
                table22.AddRow(new string[] {
                            "LookupCutomsField",
                            "automation"});
                table22.AddRow(new string[] {
                            "QATest",
                            "QAAutomationTestsUpdated"});
#line 240
    await testRunner.AndAsync("I should verify the following custom field values in warehouse receipt details in" +
                        " DFP:", ((string)(null)), table22, "And ");
#line hidden
                global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                            "Billing Client",
                            "automation"});
                table23.AddRow(new string[] {
                            "Carrier",
                            "CMA"});
                table23.AddRow(new string[] {
                            "Consignee",
                            "AgentDestination"});
                table23.AddRow(new string[] {
                            "Destination Agent",
                            "AgentDestination"});
                table23.AddRow(new string[] {
                            "Issued By",
                            "Postgress SQL II"});
                table23.AddRow(new string[] {
                            "Shipper",
                            "automation"});
                table23.AddRow(new string[] {
                            "Supplier",
                            "automation"});
#line 253
    await testRunner.AndAsync("I should verify the following parties in warehouse receipt details:", ((string)(null)), table23, "And ");
#line hidden
#line 263
    await testRunner.WhenAsync("I go to tracking tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 264
    await testRunner.ThenAsync("I should see the event \"Arrived at destination\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 266
    await testRunner.WhenAsync("I go to cargo tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 267
    await testRunner.ThenAsync("I should see the cargo items page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 268
    await testRunner.AndAsync("I should see the commodity \"UpdateCommodity\" in cargo details warehouse", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 269
    await testRunner.AndAsync("I should see the total pieces \"503 pieces\" in cargo details warehouse", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 271
    await testRunner.WhenAsync("I go to charge and invoice tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 272
    await testRunner.AndAsync("I should see the amount \"$200.00\" for the charge \"Storage Fee\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 274
    await testRunner.WhenAsync("I go to attachments tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 275
    await testRunner.AndAsync("I select the pagination number \"50\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 276
    await testRunner.AndAsync("I should see the uploaded file \"RoundPriceUpdated.xlsx\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
